SystemUI: fix crash when showing StatusBarKeyguardViewManager
java.lang.NullPointerException: Attempt to invoke virtual method 'boolean com.android.systemui.statusbar.phone.StatusBarKeyguardViewManager.isShowing()' on a null object reference
	at android.app.ActivityThread.handleCreateService(ActivityThread.java:3966)
	at android.app.ActivityThread.access$1500(ActivityThread.java:220)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1876)
	at android.os.Handler.dispatchMessage(Handler.java:107)
	at android.os.Looper.loop(Looper.java:214)
	at android.app.ActivityThread.main(ActivityThread.java:7397)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean com.android.systemui.statusbar.phone.StatusBarKeyguardViewManager.isShowing()' on a null object reference
	at com.android.systemui.statusbar.notification.DynamicPrivacyController.isInLockedDownShade(DynamicPrivacyController.java:109)
	at com.android.systemui.statusbar.notification.stack.NotificationStackScrollLayout.hasActiveClearableNotifications(NotificationStackScrollLayout.java:776)
	at com.android.systemui.statusbar.phone.NotificationPanelView.hasActiveClearableNotifications(NotificationPanelView.java:3545)
	at com.android.systemui.statusbar.phone.StatusBar.updateAreThereNotifications(StatusBar.java:1725)
	at com.android.systemui.statusbar.phone.StatusBar.setSystemUiVisibility(StatusBar.java:2651)
	at com.android.systemui.statusbar.phone.StatusBar.start(StatusBar.java:883)
	at com.google.android.systemui.statusbar.phone.StatusBarGoogle.start(StatusBarGoogle.java:15)
	at com.android.systemui.SystemBars.createStatusBarFromConfig(SystemBars.java:73)
	at com.android.systemui.SystemBars.start(SystemBars.java:39)
	at com.android.systemui.SystemUIApplication.startServicesIfNeeded(SystemUIApplication.java:209)
	at com.android.systemui.SystemUIApplication.startServicesIfNeeded(SystemUIApplication.java:145)
	at com.android.systemui.keyguard.KeyguardService.onCreate(KeyguardService.java:48)
	at android.app.ActivityThread.handleCreateService(ActivityThread.java:3954)
	... 8 more

Signed-off-by: neophyte <neophyteplayground@gmail.com>